name: Run JMeter Performance Test

on:
  schedule:
    - cron: '0 2 * * *'   # runs daily
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Run JMeter Test
      run: |
        mkdir results
        ./jmeter/bin/jmeter -n \
        -t Sample_RestAPIs.jmx \
        -l results/result.jtl \
        -e -o results/report

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: results/report
